### ISSUE TITLE
播放端无反应一直黑屏

### ISSUE THREAD

**Issue by wksnm0724** [textview10/TestH264Sender#1]
08-21 20:56:04.689 19844-19947/com.zonekey.testh264player E/MainActivity: accept a tcp connect...
08-21 20:56:22.415 19844-19990/com.zonekey.testh264player E/MainActivity: accept a tcp connect...
08-21 20:56:46.816 19844-20061/com.zonekey.testh264player E/MainActivity: accept a tcp connect...

播放器能看到发送端发过来的连接请求

**Comment by textview10** [comment]
这个要不你更新下代码吧,提供下详细日志吧,光靠这几行日志很难判断出来哪里出了问题.
