### ISSUE TITLE
你好，你代码里ip地址指的是手机的网络ip还是？两个局域网的ip不是一样的吗

### ISSUE THREAD

**Issue by lantier743865** [textview10/TestH264Sender#5]

**Comment by textview10** [comment]
是指局域网的Ip, 在同一个局域网下，每个设备都有一个不一样的Ip.

**Comment by lantier743865** [comment]
手机建立一个热点。两个手机连接就可以？



---原始邮件---
发件人: "textview10"<notifications@github.com&gt;
发送时间: 2020年10月21日(周三) 下午3:05
收件人: "textview10/TestH264Sender"<TestH264Sender@noreply.github.com&gt;;
抄送: "蓝啼儿"<635912159@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [textview10/TestH264Sender] 你好，你代码里ip地址指的是手机的网络ip还是？两个局域网的ip不是一样的吗 (#5)




 
是指局域网的Ip, 在同一个局域网下，每个设备都有一个不一样的Ip.

**Comment by textview10** [comment]
是可以的，用一个手机开个热点，另一个手机直接连这个热点就行

**Comment by lantier743865** [comment]
我们公司局域网也不行，好像有防火墙之类的。能否加个微信沟通，我微信635912159



---原始邮件---
发件人: "textview10"<notifications@github.com&gt;
发送时间: 2020年10月21日(周三) 下午3:05
收件人: "textview10/TestH264Sender"<TestH264Sender@noreply.github.com&gt;;
抄送: "蓝啼儿"<635912159@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [textview10/TestH264Sender] 你好，你代码里ip地址指的是手机的网络ip还是？两个局域网的ip不是一样的吗 (#5)




 
是指局域网的Ip, 在同一个局域网下，每个设备都有一个不一样的Ip.

**Comment by textview10** [comment]
ok，已添加。
